spring:
  application:
    name: asset-service
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://oauth.khotixs.istad.co

  config:
    import: "optional:configserver:"
  cloud:
    config:
#      uri: http://config-server:8888
      uri: http://202.178.125.77:8888

#    stream:
#      kafka:
#        binder:
#          brokers: 34.69.50.191:9092
#    bus:
#      trace:
#        enabled: true
#      refresh:
#        enabled: true
#      env:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

logging:
  level:
    io:
      minio: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: 8889
