spring:
  application:
    name: asset-service
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://khotixs-auth.devkh.asia

  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888

    stream:
      kafka:
        binder:
          brokers: 34.69.50.191:9092
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

logging:
  level:
    io:
      minio: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: 8889
  forward-headers-strategy: framework
